version: '2'

services:
  hubot:
    build:
      context: ./hubot
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - HUBOT_SLACK_TOKEN=xoxb-270710906437-B8wRMH6K5MjWYfxYb1b1P4mK
      - HUBOT_SLACK_TEAM=hubottestworkspace.slack.com
      - HUBOT_SLACK_BOTNAME=hubot
