version: '2'

services:
  redis:
    image: redis
    restart: always
    volumes:
      - ./storage/redis:/data
  hubot:
    build:
      context: ./hubot
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - hubot.env
